include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error

linter:
  rules:
    # Basic rules
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_shadowing_type_parameters: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    empty_constructor_bodies: true
    empty_catches: true
    file_names: true
    implementation_imports: true
    library_names: true
    non_constant_identifier_names: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_generic_function_type_aliases: true
    prefer_initializing_formals: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_typing_uninitialized_variables: true
    public_member_api_docs: false
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true
    use_string_buffers: true
    valid_regexps: true
