#!/bin/sh

echo "Running pre-commit checks..."

flutter pub get
flutter analyze
if [[ $? -ne 0 ]]; then
  echo ""
  echo "ERROR: There were issues found during pre-commit checks. Please fix them before committing."
  exit 1
fi
dart format --set-exit-if-changed --line-length 80 lib/
git add lib
git commit --amend --no-edit --no-verify

echo ""
echo "Pre-commit checks passed. Committing changes..."

