#!/bin/sh

echo "Running pre-commit checks..."

flutter pub get
dart format --set-exit-if-changed --line-length 80 lib/
flutter analyze
git add lib
git commit -m "formet lib all files code to maximum line length of 80 characters" --no-verify


if [[ $? -ne 0 ]]; then
  echo ""
  echo "ERROR: There were issues found during pre-commit checks. Please fix them before committing."
  exit 1
fi

echo ""
echo "Pre-commit checks passed. Committing changes..."

