name: flutter_starter
description: Flutter project that serves as a starting point or template for other Flutter projects.

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  auto_route: ^6.3.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  get_it: ^7.3.0
  http: ^0.13.5
  intl: ^0.18.1
  mockito: ^5.4.0
  shared_preferences: ^2.1.0
  velocity_x: ^0.4.1

dev_dependencies:
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  # assets:
    # - .env
