name: Clean Code Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clean-code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Format code
        run: dart format --set-exit-if-changed --line-length 80 lib/ .
